[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
gc-core = { path = "crates/gc-core" }
gc-workloads = { path = "crates/gc-workloads" }
gc-harness = { path = "crates/gc-harness" }

[profile.release]
debug = true
